import type { CommunityPostDto } from './communityPost.dto';

export const MOCK_COMMUNITY_POST_DTOS: CommunityPostDto[] = [
  {
    id: 'cp1',
    title: '청년 월세 지원, 소득 기준 어떻게 계산하나요?',
    category: '정책질문',
    content:
      '건강보험료 기준 중위소득 계산할 때 부모님 소득도 합산되는 건가요? 자취 중인데 혼자 신청 가능한지 궁금합니다.',
    authorId: 'user-rabbit-walk',
    authorName: '토끼걸음',
    createdAt: '2026-07-08',
    viewCount: 132,
    commentCount: 2,
    likeCount: 21,
    attachedPolicy: {
      id: 'p2',
      title: '청년 월세 한시 특별지원',
      category: '주거',
      deadline: '2025.06.30',
    },
  },
  {
    id: 'cp2',
    title: 'K-디지털 트레이닝 수료 후기 (국비지원)',
    category: '정책후기',
    content:
      '6개월 과정 완주했습니다. 훈련장려금은 출석률 80% 넘으면 매달 꼬박꼬박 나왔어요. 취업 연계도 도움 많이 받았습니다.',
    authorId: 'user-dev-prep',
    authorName: '개발자준비생',
    createdAt: '2026-07-07',
    viewCount: 284,
    commentCount: 1,
    likeCount: 45,
    attachedPolicy: {
      id: 'p3',
      title: 'K-디지털 트레이닝 (국비지원)',
      category: '교육',
      deadline: '2025.07.15',
    },
  },
  {
    id: 'cp3',
    title: '오늘 면접 보고 왔는데 다들 잘 지내시나요',
    category: '잡담',
    content: '떨려서 물도 제대로 못 마셨네요... 다들 취준 화이팅입니다.',
    authorId: 'user-coffee-cup',
    authorName: '커피한잔',
    createdAt: '2026-07-07',
    viewCount: 58,
    commentCount: 0,
    likeCount: 5,
    attachedPolicy: null,
  },
  {
    id: 'cp4',
    title: '청년내일채움공제 중도해지 시 환급 문의',
    category: '정책질문',
    content: '이직을 고민 중인데 중도 해지하면 그동안 적립된 금액이 어떻게 처리되는지 아시는 분?',
    authorId: 'user-job-changer',
    authorName: '이직러',
    createdAt: '2026-07-06',
    viewCount: 97,
    commentCount: 0,
    likeCount: 9,
    attachedPolicy: {
      id: 'p4',
      title: '청년내일채움공제',
      category: '일자리',
      deadline: '2025.08.31',
    },
  },
  {
    id: 'cp5',
    title: '서울시 청년수당 3개월차 진짜 도움됐어요',
    category: '정책후기',
    content:
      '구직활동 보고서만 성실히 제출하면 큰 어려움 없이 지급됩니다. 생활비 걱정 조금 덜었어요.',
    authorId: 'user-jobseeker-a',
    authorName: '취준생A',
    createdAt: '2026-07-05',
    viewCount: 176,
    commentCount: 3,
    likeCount: 38,
    attachedPolicy: {
      id: 'p7',
      title: '서울시 청년수당',
      category: '복지·문화',
      deadline: '2025.09.30',
    },
  },
  {
    id: 'cp6',
    title: '다들 주말에 뭐하세요',
    category: '잡담',
    content: '스터디 카페 vs 집 vs 도서관, 어디서 공부가 제일 잘 되는지 투표해봐요.',
    authorId: 'user-study-king',
    authorName: '스터디왕',
    createdAt: '2026-07-04',
    viewCount: 41,
    commentCount: 0,
    likeCount: 3,
    attachedPolicy: null,
  },
  {
    id: 'cp7',
    title: '청년 창업 지원금 서류 준비 팁 공유합니다',
    category: '정책후기',
    content:
      '사업계획서는 미리 3번은 고쳐 쓰는 걸 추천해요. 멘토링 신청도 같이 하면 발표 심사에 도움됩니다.',
    authorId: 'user-startup-dream',
    authorName: '창업꿈나무',
    createdAt: '2026-07-03',
    viewCount: 152,
    commentCount: 4,
    likeCount: 27,
    attachedPolicy: {
      id: 'p11',
      title: '청년 창업 지원금',
      category: '일자리',
      deadline: '2025.08.20',
    },
  },
  {
    id: 'cp8',
    title: 'K-패스 청년 할인 실제로 얼마나 환급되나요?',
    category: '정책질문',
    content: '한 달에 대중교통을 15번 이상 타면 된다고 하는데, 환급은 정확히 언제 들어오나요?',
    authorId: 'user-commute-life',
    authorName: '출퇴근러',
    createdAt: '2026-07-03',
    viewCount: 88,
    commentCount: 1,
    likeCount: 12,
    attachedPolicy: {
      id: 'p12',
      title: '청년 대중교통비 지원 (K-패스)',
      category: '복지·문화',
      deadline: '2025.12.31',
    },
  },
  {
    id: 'cp9',
    title: '전세자금 대출 이자 지원 후기, 생각보다 절차 간단해요',
    category: '정책후기',
    content:
      '경기도 거주 조건만 맞으면 은행 방문 한 번으로 신청 끝났습니다. 이자 부담이 확실히 줄어요.',
    authorId: 'user-gyeonggi-life',
    authorName: '경기청년',
    createdAt: '2026-07-02',
    viewCount: 121,
    commentCount: 2,
    likeCount: 19,
    attachedPolicy: {
      id: 'p13',
      title: '청년 전세자금 대출 이자 지원',
      category: '주거',
      deadline: '2025.09.30',
    },
  },
  {
    id: 'cp10',
    title: '오늘도 이력서 열 통 넣었습니다',
    category: '잡담',
    content: '취업 시장이 정말 어렵네요. 다들 어떻게 멘탈 관리하시는지 궁금해요.',
    authorId: 'user-resume-machine',
    authorName: '이력서머신',
    createdAt: '2026-07-02',
    viewCount: 64,
    commentCount: 3,
    likeCount: 15,
    attachedPolicy: null,
  },
  {
    id: 'cp11',
    title: '청년 정책참여단 활동 후기 남깁니다',
    category: '정책후기',
    content:
      '한 달에 한 번 회의 참석하고 정책 제안서 작성하는 활동인데, 실제 정책에 반영된 것도 있어요.',
    authorId: 'user-policy-voice',
    authorName: '정책목소리',
    createdAt: '2026-07-01',
    viewCount: 73,
    commentCount: 1,
    likeCount: 22,
    attachedPolicy: {
      id: 'p14',
      title: '청년 정책참여단 모집',
      category: '참여·권리',
      deadline: '2025.07.31',
    },
  },
  {
    id: 'cp12',
    title: '국민내일배움카드 수강료 지원 비율이 궁금해요',
    category: '정책질문',
    content: '희망 강좌마다 지원 비율이 다르다고 들었는데, 어디서 확인할 수 있나요?',
    authorId: 'user-learn-more',
    authorName: '배움러',
    createdAt: '2026-07-01',
    viewCount: 95,
    commentCount: 0,
    likeCount: 8,
    attachedPolicy: {
      id: 'p6',
      title: '국민내일배움카드',
      category: '교육',
      deadline: '2025.12.31',
    },
  },
  {
    id: 'cp13',
    title: '자취 6개월차, 월세 지원 신청하고 숨통 트였어요',
    category: '정책후기',
    content:
      '매달 20만원씩 지원받으니 확실히 생활비 여유가 생기네요. 서류만 미리 준비하면 어렵지 않아요.',
    authorId: 'user-solo-living',
    authorName: '자취생활',
    createdAt: '2026-06-30',
    viewCount: 143,
    commentCount: 2,
    likeCount: 31,
    attachedPolicy: {
      id: 'p2',
      title: '청년 월세 한시 특별지원',
      category: '주거',
      deadline: '2025.06.30',
    },
  },
  {
    id: 'cp14',
    title: '이번 주말 정책 박람회 가보신 분 계신가요',
    category: '잡담',
    content:
      '청년 정책 한 자리에서 다 볼 수 있다고 해서 가보려고 하는데, 후기 있으면 공유해주세요.',
    authorId: 'user-fair-goer',
    authorName: '박람회탐방',
    createdAt: '2026-06-30',
    viewCount: 37,
    commentCount: 0,
    likeCount: 4,
    attachedPolicy: null,
  },
  {
    id: 'cp15',
    title: '서울시 청년수당 구직활동 보고서 양식 공유합니다',
    category: '정책후기',
    content:
      '매번 새로 만들지 마시고 이 양식 그대로 쓰시면 됩니다. 심사에서 반려된 적 한 번도 없어요.',
    authorId: 'user-jobseeker-a',
    authorName: '취준생A',
    createdAt: '2026-06-29',
    viewCount: 201,
    commentCount: 5,
    likeCount: 52,
    attachedPolicy: {
      id: 'p7',
      title: '서울시 청년수당',
      category: '복지·문화',
      deadline: '2025.09.30',
    },
  },
  {
    id: 'cp16',
    title: '청년내일저축계좌 3년 만기 후기',
    category: '정책후기',
    content: '드디어 만기 찾았습니다. 매달 10만원씩 꾸준히 넣은 보람이 있네요.',
    authorId: 'user-saving-goal',
    authorName: '저축목표',
    createdAt: '2026-06-29',
    viewCount: 168,
    commentCount: 3,
    likeCount: 44,
    attachedPolicy: {
      id: 'p8',
      title: '청년내일저축계좌',
      category: '복지·문화',
      deadline: '2025.10.15',
    },
  },
];
