import { UNRESTRICTED_CONDITION } from '../model/policyConditions';
import type { PolicyDto, RecentlyViewedPolicyDto } from './policy.dto';

export const MOCK_POLICY_DTOS: PolicyDto[] = [
  {
    id: 'p1',
    title: '청년 디지털 일자리 지원 사업',
    category: '일자리',
    region: '서울특별시',
    tag: 'HIGH',
    organizationName: '고용노동부',
    description:
      'IT 분야 실무 경험과 교육을 제공하고 취업 연계를 지원하는 고용노동부 주관 사업입니다.',
    target: '만 19~34세',
    eligibleStatuses: ['취업준비', '미취업'],
    ageMin: 19,
    ageMax: 34,
    maritalCondition: UNRESTRICTED_CONDITION,
    majorCondition: UNRESTRICTED_CONDITION,
    specialConditionTags: [],
    incomeMax: null,
    deadline: '2025.06.30',
    logoType: 'job',
    supportContent: '청년 채용 기업에 인건비 월 최대 190만원 지원 및 실무 교육 제공',
    additionalQualification: '만 19세 이상 34세 이하의 미취업 청년',
    applicationMethod: '워크넷 청년일자리사업 페이지에서 온라인 접수',
    submissionDocuments: '이력서, 자기소개서, 최종학력 졸업(예정)증명서',
    screeningMethod: null,
    participationRestriction: '동일 사업 참여 이력이 있는 기업은 재신청 불가',
    details: ['근무조건: 주 30시간 이상 근로, 3개월 이상 채용 계약'],
    link: 'https://www.work.go.kr',
  },
  {
    id: 'p2',
    title: '청년 월세 한시 특별지원',
    category: '주거',
    region: '서울특별시',
    tag: '추천',
    organizationName: '국토교통부',
    description:
      '서울 및 전국 무주택 청년의 주거비 부담 경감을 위해 실제 납부하는 월세를 지원합니다.',
    target: '만 19~34세',
    eligibleStatuses: ['전체'],
    ageMin: 19,
    ageMax: 34,
    maritalCondition: UNRESTRICTED_CONDITION,
    majorCondition: UNRESTRICTED_CONDITION,
    specialConditionTags: [],
    incomeMax: 2000,
    deadline: '2025.06.30',
    logoType: 'home',
    supportContent: '실제 납부하는 월세 범위 내에서 월 최대 20만원까지 최장 12개월 분할 지원',
    additionalQualification: '부모와 별도 거주하는 무주택 청년 중 소득 기준 충족자',
    applicationMethod: '복지로 온라인 신청 또는 주소지 관할 행정복지센터 방문 신청',
    submissionDocuments: '임대차계약서, 통장사본, 소득금액증명원',
    screeningMethod: '서류 요건 충족 여부 행정 확인 후 순차 지급',
    participationRestriction: '주택 소유자, 다른 월세 지원사업 중복 수급자는 제외',
    details: ['임차기준: 임차보증금 5천만원 이하 및 월세 60만원 이하'],
    link: 'https://www.bokjiro.go.kr',
  },
  {
    id: 'p3',
    title: 'K-디지털 트레이닝 (국비지원)',
    category: '교육',
    region: '서울특별시',
    tag: 'HIGH',
    organizationName: '고용노동부',
    description:
      '디지털, AI, 신기술 핵심 실무 중심 교육을 통해 고소득 기술 취업 역량을 극대화하는 과정입니다.',
    target: '만 19~34세',
    eligibleStatuses: ['취업준비', '대학생', '미취업'],
    ageMin: 19,
    ageMax: 34,
    maritalCondition: UNRESTRICTED_CONDITION,
    majorCondition: '공학계열',
    specialConditionTags: [],
    incomeMax: null,
    deadline: '2025.07.15',
    logoType: 'education',
    supportContent: '수강료 전액 지원(국비무료) 및 월 최대 31만 6천원의 훈련장려금 지급',
    additionalQualification: '만 19세~34세 대학 졸업(예정)자 및 미취업 청년, 공학계열 전공자 한정',
    applicationMethod: 'HRD-Net에서 과정 검색 후 온라인 수강 신청',
    submissionDocuments: '수강신청서, 재직·졸업증명서, 훈련장려금 지급 계좌 사본',
    screeningMethod: '선착순 접수 및 과정별 사전 상담 통과자 선발',
    participationRestriction: null,
    details: ['교육기간: 평균 6개월 (평일 주간 8시간 밀착 교육)'],
    link: 'https://www.hrd.go.kr',
  },
  {
    id: 'p4',
    title: '청년내일채움공제',
    category: '일자리',
    region: '경기도',
    tag: 'NEW',
    organizationName: '중소벤처기업부',
    description:
      '중소기업 취업 청년의 자산 형성을 지원하여 장기 근속을 유도하고 대기업과의 격차를 완화합니다.',
    target: '만 15~34세',
    eligibleStatuses: ['직장인'],
    ageMin: 15,
    ageMax: 34,
    maritalCondition: UNRESTRICTED_CONDITION,
    majorCondition: UNRESTRICTED_CONDITION,
    specialConditionTags: [],
    incomeMax: null,
    deadline: '2025.08.31',
    logoType: 'job',
    supportContent: '청년이 2년간 300만원을 적립하면 정부와 기업이 적립해 총 1,200만원 자산 마련',
    additionalQualification: '5인 이상 중소기업에 신규 취업한 청년 및 해당 기업',
    applicationMethod: '청년내일채움공제 홈페이지에서 청약 신청',
    submissionDocuments: '취업사실확인서, 4대보험 가입내역확인서, 기업 사업자등록증 사본',
    screeningMethod: null,
    participationRestriction: '동일 사업장에서 과거 청약 후 중도해지한 이력이 있으면 재가입 제한',
    details: ['가입기간: 정규직 입사일로부터 6개월 이내 신청 필수'],
    link: 'https://www.sbcof.or.kr',
  },
  {
    id: 'p5',
    title: '청년 주거급여 분리지급',
    category: '주거',
    region: '서울특별시',
    tag: '추천',
    organizationName: '국토교통부',
    description:
      '주거급여 수급 가구 중 학업이나 취업으로 부모와 타 지역에 거주하는 청년에게 별도로 급여를 지급합니다.',
    target: '만 19~30세',
    eligibleStatuses: ['전체'],
    ageMin: 19,
    ageMax: 30,
    maritalCondition: '미혼',
    majorCondition: UNRESTRICTED_CONDITION,
    specialConditionTags: [],
    incomeMax: 2400,
    deadline: '2025.12.31',
    logoType: 'home',
    supportContent: '부모와 떨어진 별도 가구원에 대해 서울 및 해당 지역 기준 임차료 지급',
    additionalQualification: '주거급여 수급 가구원 중 만 19세 이상 30세 미만 미혼 자녀',
    applicationMethod: '주민등록상 부모 거주지 읍면동 행정복지센터 방문 혹은 복지로 온라인 신청',
    submissionDocuments: '임대차계약서, 전입세대열람원',
    screeningMethod: null,
    participationRestriction: null,
    details: [],
    link: 'https://www.bokjiro.go.kr',
  },
  {
    id: 'p6',
    title: '국민내일배움카드',
    category: '교육',
    region: '전국',
    tag: 'NEW',
    organizationName: '고용노동부',
    description:
      '취업준비생 및 이직 희망 청년이 스스로 직업 능력을 개발하도록 평생교육 배움 비용을 보조합니다.',
    target: '전체',
    eligibleStatuses: ['전체'],
    ageMin: null,
    ageMax: null,
    maritalCondition: UNRESTRICTED_CONDITION,
    majorCondition: UNRESTRICTED_CONDITION,
    specialConditionTags: [],
    incomeMax: null,
    deadline: '2025.12.31',
    logoType: 'education',
    supportContent: '5년간 300만원에서 최대 500만원까지의 훈련 직무 수강 비용 45~85% 지원',
    additionalQualification: '일반 직장인, 미취업 청년, 졸업 예정 대학생 등 누구나 발급 가능',
    applicationMethod: 'HRD-Net 또는 고용센터 방문을 통한 카드 발급 신청',
    submissionDocuments: null,
    screeningMethod: null,
    participationRestriction:
      '공무원, 사립학교 교직원, 연 매출 1억 5천만원 이상 자영업자 등은 제외',
    details: [],
    link: 'https://www.hrd.go.kr',
  },
  {
    id: 'p7',
    title: '서울시 청년수당',
    category: '복지·문화',
    region: '서울특별시',
    tag: 'HIGH',
    organizationName: '서울특별시',
    description:
      '서울 거주 미취업 청년들의 안정적인 구직활동과 진로 개척을 돕기 위해 생계 보조 청년 수당을 지급합니다.',
    target: '만 19~34세',
    eligibleStatuses: ['취업준비', '미취업'],
    ageMin: 19,
    ageMax: 34,
    maritalCondition: UNRESTRICTED_CONDITION,
    majorCondition: UNRESTRICTED_CONDITION,
    specialConditionTags: [],
    incomeMax: 3100,
    deadline: '2025.09.30',
    logoType: 'heart',
    supportContent: '월 50만원씩 최대 6개월간 매월 체크카드 바우처 포인트 형태로 지원금 지급',
    additionalQualification: '서울 거주 만 19세~34세 졸업 후 미취업자 중 중위소득 150% 이하',
    applicationMethod: '청년몽땅정보통 홈페이지에서 온라인 신청',
    submissionDocuments: '졸업증명서, 소득금액증명원, 구직활동계획서',
    screeningMethod: '자격요건 서류 심사 후 예산 범위 내 선발',
    participationRestriction: '구직촉진수당 등 유사 목적의 정부 지원사업과 중복 수급 불가',
    details: ['필수활동: 주간 구직 활동 보고서 제출 및 진로 프로그램 참여'],
    link: 'https://youth.seoul.go.kr',
  },
  {
    id: 'p8',
    title: '청년내일저축계좌',
    category: '복지·문화',
    region: '부산광역시',
    tag: '추천',
    organizationName: '보건복지부',
    description:
      '일하는 청년들이 주거, 취업 등으로 인한 자립 기반을 갖출 수 있도록 정부가 목돈을 함께 마련해 줍니다.',
    target: '만 19~34세',
    eligibleStatuses: ['직장인', '창업자'],
    ageMin: 19,
    ageMax: 34,
    maritalCondition: UNRESTRICTED_CONDITION,
    majorCondition: UNRESTRICTED_CONDITION,
    specialConditionTags: [],
    incomeMax: 2600,
    deadline: '2025.10.15',
    logoType: 'heart',
    supportContent: '본인 저축 월 10만원당 정부 지원금 10만~30만원을 3년간 1:1 매칭 적립',
    additionalQualification: '일하고 있는 만 19세~34세 이하 청년 중 소득기준 충족자',
    applicationMethod: '복지로 온라인 신청 또는 주소지 관할 행정복지센터 방문 신청',
    submissionDocuments: '재직증명서 또는 사업자등록증, 소득금액증명원, 통장사본',
    screeningMethod: null,
    participationRestriction: '가입 기간 중 3년 내 근로·사업활동을 지속하지 않으면 지급 제한',
    details: ['만기적립금: 3년 만기 시 최대 1,440만원 및 근로소득공제금 추가 적립'],
    link: 'https://www.bokjiro.go.kr',
  },
  {
    id: 'p9',
    title: '청년문화예술패스',
    category: '복지·문화',
    region: '전국',
    tag: 'NEW',
    organizationName: '문화체육관광부',
    description:
      '사회에 첫 발을 내딛는 청년들에게 다채로운 문화생활과 연극, 전시, 음악 관람 비용을 전폭적으로 제공합니다.',
    target: '만 19세',
    eligibleStatuses: ['전체'],
    ageMin: 19,
    ageMax: 19,
    maritalCondition: UNRESTRICTED_CONDITION,
    majorCondition: UNRESTRICTED_CONDITION,
    specialConditionTags: [],
    incomeMax: null,
    deadline: '2025.11.30',
    logoType: 'heart',
    supportContent: '공연 및 전시 관람료로 사용할 수 있는 포인트 최대 15만원 즉시 지급',
    additionalQualification: '만 19세가 되는 국내 거주 모든 청년 (선착순 신청)',
    applicationMethod: '청년문화예술패스 홈페이지 또는 앱에서 회원가입 후 신청',
    submissionDocuments: null,
    screeningMethod: null,
    participationRestriction: null,
    details: ['사용처: 인터파크, 예스24 등 지정 티켓 판매처에서 포인트로 구매 가능'],
    link: 'https://www.kopis.or.kr',
  },
  {
    id: 'p10',
    title: '정부부처 청년인턴',
    category: '참여·권리',
    region: '전국',
    tag: '추천',
    organizationName: '인사혁신처',
    description:
      '중앙 행정 기관의 입법, 사업 진행 등의 부처 행정 실무를 인턴십으로 체험하고 참관할 기회를 제공합니다.',
    target: '만 19~34세',
    eligibleStatuses: ['취업준비', '대학생', '대학원생', '미취업'],
    ageMin: 19,
    ageMax: 34,
    maritalCondition: UNRESTRICTED_CONDITION,
    majorCondition: UNRESTRICTED_CONDITION,
    specialConditionTags: [],
    incomeMax: null,
    deadline: '2025.06.15',
    logoType: 'hand',
    supportContent: '국가 공공 기관 인턴 근무 경력 증명서 발급 및 월 고정 기본급 및 수당 지급',
    additionalQualification: '만 19세 이상 34세 이하의 미취업자 (학력 제한 없음)',
    applicationMethod: '나라일터(잡알리오) 채용 공고를 통한 온라인 접수',
    submissionDocuments: '이력서, 자기소개서, 최종학력 증명서',
    screeningMethod: '서류 전형 및 면접 전형',
    participationRestriction: null,
    details: ['근무기간: 부처별 6개월 이내 단기 채용'],
    link: 'https://www.jobis.or.kr',
  },
  {
    id: 'p11',
    title: '청년 창업 지원금',
    category: '일자리',
    region: '전국',
    tag: 'NEW',
    organizationName: '중소벤처기업부',
    description:
      '예비 창업자 및 창업 3년 이내 청년에게 사업화 자금과 멘토링을 함께 지원하는 사업입니다.',
    target: '만 19~39세',
    eligibleStatuses: ['창업자', '취업준비'],
    ageMin: 19,
    ageMax: 39,
    maritalCondition: UNRESTRICTED_CONDITION,
    majorCondition: UNRESTRICTED_CONDITION,
    specialConditionTags: [],
    incomeMax: null,
    deadline: '2025.08.20',
    logoType: 'job',
    supportContent: '사업화 자금 최대 5천만원 및 전담 멘토 1:1 컨설팅 제공',
    additionalQualification: '만 19세 이상 39세 이하 예비 창업자 및 창업 3년 이내 대표',
    applicationMethod: 'K-스타트업 홈페이지에서 온라인 접수',
    submissionDocuments: '사업계획서, 사업자등록증 사본(창업자), 대표자 신분증 사본',
    screeningMethod: '사업계획서 서류 심사 및 발표 평가',
    participationRestriction: '동일 사업 기수 내 중복 선정 불가',
    details: [],
    link: 'https://www.k-startup.go.kr',
  },
  {
    id: 'p12',
    title: '청년 대중교통비 지원 (K-패스)',
    category: '복지·문화',
    region: '전국',
    tag: '추천',
    organizationName: '국토교통부',
    description:
      '월 15회 이상 대중교통을 이용하는 청년에게 지출 금액 일부를 다음 달에 환급해 줍니다.',
    target: '만 19~34세',
    eligibleStatuses: ['전체'],
    ageMin: 19,
    ageMax: 34,
    maritalCondition: UNRESTRICTED_CONDITION,
    majorCondition: UNRESTRICTED_CONDITION,
    specialConditionTags: [],
    incomeMax: null,
    deadline: '2025.12.31',
    logoType: 'heart',
    supportContent: '월 대중교통 지출액의 30%를 익월 환급 (최대 60회 한도)',
    additionalQualification: '만 19세 이상 34세 이하 K-패스 카드 발급자',
    applicationMethod: 'K-패스 앱 또는 카드사 홈페이지에서 청년 등급 등록',
    submissionDocuments: null,
    screeningMethod: null,
    participationRestriction: null,
    details: [],
    link: 'https://korea-pass.kr',
  },
  {
    id: 'p13',
    title: '청년 전세자금 대출 이자 지원',
    category: '주거',
    region: '경기도',
    tag: 'HIGH',
    organizationName: '경기도',
    description: '무주택 청년의 전세자금 대출 이자 부담을 낮춰 안정적인 주거 마련을 지원합니다.',
    target: '만 19~39세',
    eligibleStatuses: ['전체'],
    ageMin: 19,
    ageMax: 39,
    maritalCondition: '미혼',
    majorCondition: UNRESTRICTED_CONDITION,
    specialConditionTags: [],
    incomeMax: 3500,
    deadline: '2025.09.30',
    logoType: 'home',
    supportContent: '전세자금 대출 이자의 연 최대 2%p 차액 보전',
    additionalQualification: '경기도 거주 무주택 미혼 청년 중 소득 기준 충족자',
    applicationMethod: '경기도 청년포털에서 온라인 신청',
    submissionDocuments: '임대차계약서, 전세자금 대출 실행 확인서, 소득금액증명원',
    screeningMethod: null,
    participationRestriction: null,
    details: ['대출한도: 임차보증금 3억원 이하 주택'],
    link: 'https://www.gg.go.kr',
  },
  {
    id: 'p14',
    title: '청년 정책참여단 모집',
    category: '참여·권리',
    region: '전국',
    tag: 'NEW',
    organizationName: '국무조정실',
    description:
      '청년 정책 기획 단계부터 직접 참여해 의견을 제안하고 정책 모니터링 활동을 수행합니다.',
    target: '만 19~34세',
    eligibleStatuses: ['전체'],
    ageMin: 19,
    ageMax: 34,
    maritalCondition: UNRESTRICTED_CONDITION,
    majorCondition: UNRESTRICTED_CONDITION,
    specialConditionTags: [],
    incomeMax: null,
    deadline: '2025.07.31',
    logoType: 'hand',
    supportContent: '활동비 지급 및 정책 제안 채택 시 인센티브 제공',
    additionalQualification: '만 19세 이상 34세 이하 청년 누구나 지원 가능',
    applicationMethod: '청년정책 통합 플랫폼에서 온라인 신청',
    submissionDocuments: null,
    screeningMethod: '지원서 심사 후 선발',
    participationRestriction: '월 1회 정기 회의 2회 이상 불참 시 활동 중단',
    details: ['활동기간: 6개월, 월 1회 정기 회의 참석 필수'],
    link: 'https://youth.go.kr',
  },
  {
    id: 'p_missing',
    title: '청년 취업지원 프로그램',
    category: '일자리',
    region: '전국',
    tag: 'NEW',
    organizationName: '확인 불가',
    description: '현재 공식 원본을 확인할 수 없습니다. 저장한 기록과 메모는 유지됩니다.',
    target: '전체',
    eligibleStatuses: ['전체'],
    ageMin: null,
    ageMax: null,
    maritalCondition: UNRESTRICTED_CONDITION,
    majorCondition: UNRESTRICTED_CONDITION,
    specialConditionTags: [],
    incomeMax: null,
    deadline: '원본확인불가',
    logoType: 'job',
    supportContent: null,
    additionalQualification: null,
    applicationMethod: null,
    submissionDocuments: null,
    screeningMethod: null,
    participationRestriction: null,
    details: [
      '현재 이 정책의 원본 공고가 만료되었거나 삭제되었습니다. 개인 메모 및 이력은 유지됩니다.',
    ],
    link: '#',
    isSourceMissing: true,
  },
];

export const RECENTLY_VIEWED_POLICY_DTOS: RecentlyViewedPolicyDto[] = [
  { id: 'p2', category: '주거', title: '청년 월세 한시 특별지원', date: '2025.05.28' },
  { id: 'p4', category: '일자리', title: '청년내일채움공제', date: '2025.05.27' },
  { id: 'p6', category: '교육', title: '국민내일배움카드', date: '2025.05.26' },
];
